CREATE TABLE 'caravan_buff_disp' ('id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'effect_id' INTEGER NOT NULL, 'category' INTEGER NOT NULL, 'icon_id' INTEGER NOT NULL, 'description' TEXT NOT NULL, 'count_from' INTEGER NOT NULL, 'count_to' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `caravan_buff_disp` VALUES (/*id*/1, /*type*/1, /*effect_id*/52001, /*category*/1, /*icon_id*/1, /*description*/"【料理】ダイスが2個に増える", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/2, /*type*/1, /*effect_id*/52002, /*category*/1, /*icon_id*/1, /*description*/"【料理】ダイスの目が必ず「1」になる", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/3, /*type*/1, /*effect_id*/52002, /*category*/3, /*icon_id*/2, /*description*/"【料理】次のターン数のカウントをスキップする", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/4, /*type*/1, /*effect_id*/52004, /*category*/1, /*icon_id*/1, /*description*/"【料理】ダイスの目が必ず「4」になる", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/5, /*type*/1, /*effect_id*/52006, /*category*/1, /*icon_id*/1, /*description*/"【料理】ダイスの目が\n「4・5・6」のみになる", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/6, /*type*/1, /*effect_id*/52007, /*category*/1, /*icon_id*/1, /*description*/"【料理】ダイスの目が1回目は必ず「3」に、2回目は必ず「6」になる", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/7, /*type*/1, /*effect_id*/52003, /*category*/1, /*icon_id*/1, /*description*/"【料理】ダイスの目が必ず「5」になる", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/8, /*type*/1, /*effect_id*/52008, /*category*/2, /*icon_id*/7, /*description*/"【料理】マイルマスの獲得マイルが200%アップする", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/9, /*type*/2, /*effect_id*/4, /*category*/3, /*icon_id*/2, /*description*/"【イベント】次のターン数のカウントをスキップする", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/10, /*type*/2, /*effect_id*/5, /*category*/2, /*icon_id*/3, /*description*/"【イベント】マイルマスの獲得マイルが100%アップする", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/11, /*type*/2, /*effect_id*/6, /*category*/2, /*icon_id*/5, /*description*/"【イベント】ミニゲームの獲得マイルが100%アップする", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/12, /*type*/2, /*effect_id*/7, /*category*/3, /*icon_id*/4, /*description*/"【イベント】マイルショップの全商品が20%以上割引される", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/13, /*type*/1, /*effect_id*/52009, /*category*/1, /*icon_id*/1, /*description*/"【料理】ダイスの目が1回目は必ず「8」に、2回目は必ず「1」になる", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/14, /*type*/1, /*effect_id*/52010, /*category*/2, /*icon_id*/6, /*description*/"【料理】「マイルマス」「トレ\nジャーマス」「ショップマス」のRANKが1つ上がる", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/15, /*type*/1, /*effect_id*/52011, /*category*/1, /*icon_id*/1, /*description*/"【料理】ダイスの目が1回目は必ず「2」に、2回目は必ず「7」になる", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/16, /*type*/1, /*effect_id*/52012, /*category*/1, /*icon_id*/1, /*description*/"【料理】ダイスの目が\n「1・2・3」のみになる", /*count_from*/0, /*count_to*/0);
INSERT INTO `caravan_buff_disp` VALUES (/*id*/17, /*type*/1, /*effect_id*/52012, /*category*/3, /*icon_id*/2, /*description*/"【料理】次のターン数のカウントをスキップする", /*count_from*/0, /*count_to*/0);
CREATE INDEX 'caravan_buff_disp_0_type_1_effect_id' on 'caravan_buff_disp'('type','effect_id');
