CREATE TABLE 'clan_battle_recommend_data' ('level_id' INTEGER NOT NULL, 'recommend_group' INTEGER NOT NULL, 'level_from' INTEGER NOT NULL, 'level_to' INTEGER NOT NULL, 'atack_party_count' INTEGER NOT NULL, 'magic_party_count' INTEGER NOT NULL, PRIMARY KEY('level_id'));
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/1, /*recommend_group*/1, /*level_from*/10, /*level_to*/46, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/2, /*recommend_group*/1, /*level_from*/47, /*level_to*/66, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/3, /*recommend_group*/1, /*level_from*/67, /*level_to*/86, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/4, /*recommend_group*/2, /*level_from*/87, /*level_to*/106, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/5, /*recommend_group*/2, /*level_from*/107, /*level_to*/126, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/6, /*recommend_group*/2, /*level_from*/127, /*level_to*/146, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/7, /*recommend_group*/3, /*level_from*/147, /*level_to*/166, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/8, /*recommend_group*/3, /*level_from*/167, /*level_to*/176, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/9, /*recommend_group*/3, /*level_from*/177, /*level_to*/186, /*atack_party_count*/2, /*magic_party_count*/2);
CREATE INDEX 'clan_battle_recommend_data_0_recommend_group' on 'clan_battle_recommend_data'('recommend_group');
