CREATE TABLE 'clan_battle_recommend_data' ('level_id' INTEGER NOT NULL, 'recommend_group' INTEGER NOT NULL, 'level_from' INTEGER NOT NULL, 'level_to' INTEGER NOT NULL, 'atack_party_count' INTEGER NOT NULL, 'magic_party_count' INTEGER NOT NULL, PRIMARY KEY('level_id'));
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/1, /*recommend_group*/1, /*level_from*/10, /*level_to*/43, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/2, /*recommend_group*/1, /*level_from*/44, /*level_to*/63, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/3, /*recommend_group*/1, /*level_from*/64, /*level_to*/83, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/4, /*recommend_group*/2, /*level_from*/84, /*level_to*/103, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/5, /*recommend_group*/2, /*level_from*/104, /*level_to*/123, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/6, /*recommend_group*/2, /*level_from*/124, /*level_to*/143, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/7, /*recommend_group*/3, /*level_from*/144, /*level_to*/163, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/8, /*recommend_group*/3, /*level_from*/164, /*level_to*/173, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/9, /*recommend_group*/3, /*level_from*/174, /*level_to*/183, /*atack_party_count*/2, /*magic_party_count*/2);
CREATE INDEX 'clan_battle_recommend_data_0_recommend_group' on 'clan_battle_recommend_data'('recommend_group');
