CREATE TABLE 'clan_battle_recommend_data' ('level_id' INTEGER NOT NULL, 'recommend_group' INTEGER NOT NULL, 'level_from' INTEGER NOT NULL, 'level_to' INTEGER NOT NULL, 'atack_party_count' INTEGER NOT NULL, 'magic_party_count' INTEGER NOT NULL, PRIMARY KEY('level_id'));
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/1, /*recommend_group*/1, /*level_from*/10, /*level_to*/49, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/2, /*recommend_group*/1, /*level_from*/50, /*level_to*/69, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/3, /*recommend_group*/1, /*level_from*/70, /*level_to*/89, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/4, /*recommend_group*/2, /*level_from*/90, /*level_to*/109, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/5, /*recommend_group*/2, /*level_from*/110, /*level_to*/129, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/6, /*recommend_group*/2, /*level_from*/130, /*level_to*/149, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/7, /*recommend_group*/3, /*level_from*/150, /*level_to*/169, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/8, /*recommend_group*/3, /*level_from*/170, /*level_to*/179, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/9, /*recommend_group*/3, /*level_from*/180, /*level_to*/189, /*atack_party_count*/2, /*magic_party_count*/2);
CREATE INDEX 'clan_battle_recommend_data_0_recommend_group' on 'clan_battle_recommend_data'('recommend_group');
