CREATE TABLE 'custom_mypage' ('still_id' INTEGER NOT NULL, 'group_id' INTEGER NOT NULL, 'still_group_id' INTEGER NOT NULL, 'still_name' TEXT NOT NULL, 'vertical_still_flg' INTEGER NOT NULL, 'scroll_direction' INTEGER NOT NULL, PRIMARY KEY('still_id'));
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000000, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu01scene1", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000001, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu01scene2", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000002, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu01scene3", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000003, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu01scene4", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000004, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu02scene1", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000005, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu02scene2", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000006, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu02scene3", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000007, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu02scene4", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000008, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu02scene5", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000009, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu02scene6", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000010, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu03scene1", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000011, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu03scene2", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000012, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu03scene3", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000013, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu03scene4", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000014, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu03scene5", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000015, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"Menu03scene6", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000016, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"OPscene1", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000017, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"OPscene2", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000018, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"OPscene3", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000019, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"OPscene4", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000020, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"OPscene5", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000021, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"OPscene6", /*vertical_still_flg*/0, /*scroll_direction*/0);
INSERT INTO `custom_mypage` VALUES (/*still_id*/9000022, /*group_id*/10001, /*still_group_id*/0, /*still_name*/"アニメオリジナル　コッコロカスタムマイページ", /*vertical_still_flg*/0, /*scroll_direction*/0);
CREATE INDEX 'custom_mypage_0_still_group_id' on 'custom_mypage'('still_group_id');
