CREATE TABLE 'event_gacha_data' ('gacha_id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'gacha_name' TEXT NOT NULL, 'item_type' INTEGER NOT NULL, 'item_id' INTEGER NOT NULL, 'cost' INTEGER NOT NULL, 'repeat_step' INTEGER NOT NULL, PRIMARY KEY('gacha_id'));
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10001, /*event_id*/10001, /*gacha_name*/"ハツネボックスガチャ", /*item_type*/2, /*item_id*/60002, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10002, /*event_id*/10002, /*gacha_name*/"リトル・リリカル・アドベンチャーズ討伐証交換", /*item_type*/2, /*item_id*/60012, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10004, /*event_id*/10004, /*gacha_name*/"デンジャラスバカンス！渚のグルメプリンセス", /*item_type*/2, /*item_id*/60032, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10005, /*event_id*/10005, /*gacha_name*/"タマキとミフユの無人島０ルピ生活", /*item_type*/2, /*item_id*/60042, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10006, /*event_id*/10006, /*gacha_name*/"黒鉄の亡霊", /*item_type*/2, /*item_id*/60052, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10007, /*event_id*/10007, /*gacha_name*/"トリックオアプリン！約束のハロウィンパーティー", /*item_type*/2, /*item_id*/60062, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10008, /*event_id*/10008, /*gacha_name*/"トワイライトブレイカーズ", /*item_type*/2, /*item_id*/60072, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10009, /*event_id*/10009, /*gacha_name*/"忘却のキャロル", /*item_type*/2, /*item_id*/60082, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10010, /*event_id*/10010, /*gacha_name*/"新春トゥインクルクライシス！", /*item_type*/2, /*item_id*/60092, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10011, /*event_id*/10011, /*gacha_name*/"バトルオブバレンタイン！想いぶつかるスウィートバトル", /*item_type*/2, /*item_id*/60102, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10012, /*event_id*/10012, /*gacha_name*/"王都の名探偵　嘆きの追跡者（ストーカー）", /*item_type*/2, /*item_id*/60112, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10013, /*event_id*/10013, /*gacha_name*/"アストルムに咲く双輪の華", /*item_type*/2, /*item_id*/60122, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10014, /*event_id*/10014, /*gacha_name*/"復刻ハツネのプレゼント大作戦", /*item_type*/2, /*item_id*/60132, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10015, /*event_id*/10015, /*gacha_name*/"ショーグン道中記　白翼のサムライ", /*item_type*/2, /*item_id*/60142, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10016, /*event_id*/10016, /*gacha_name*/"復刻リトル・リリカル・アドベンチャーズ！", /*item_type*/2, /*item_id*/60152, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10017, /*event_id*/10017, /*gacha_name*/"Re:ゼロから集まる異世界食卓", /*item_type*/2, /*item_id*/60162, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10018, /*event_id*/10018, /*gacha_name*/"復刻ヴァンパイアハンターwithイリヤ", /*item_type*/2, /*item_id*/60172, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10019, /*event_id*/10019, /*gacha_name*/"スズナレインボーステージ！", /*item_type*/2, /*item_id*/60182, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10020, /*event_id*/10020, /*gacha_name*/"復刻デンジャラスバカンス！渚のグルメプリンセス", /*item_type*/2, /*item_id*/60192, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10021, /*event_id*/10021, /*gacha_name*/"真夏のマホマホ王国 波打ち際のソウルサマー！", /*item_type*/2, /*item_id*/60202, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10022, /*event_id*/10022, /*gacha_name*/"タマキとミフユの無人島０ルピ生活", /*item_type*/2, /*item_id*/60212, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10023, /*event_id*/10023, /*gacha_name*/"森の臆病者と聖なる学舎の異端児", /*item_type*/2, /*item_id*/60222, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10024, /*event_id*/10024, /*gacha_name*/"黒鉄の亡霊（ナイトメア）", /*item_type*/2, /*item_id*/60232, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10025, /*event_id*/10025, /*gacha_name*/"リトル・ブレイブ・ハロウィンナイト！", /*item_type*/2, /*item_id*/60242, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10026, /*event_id*/10026, /*gacha_name*/"トリックオアプリン！約束のハロウィンパーティー", /*item_type*/2, /*item_id*/60252, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10027, /*event_id*/10027, /*gacha_name*/"ドラゴンエクスプローラーズ", /*item_type*/2, /*item_id*/60262, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10028, /*event_id*/10028, /*gacha_name*/"トワイライトブレイカーズ", /*item_type*/2, /*item_id*/60272, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10029, /*event_id*/10029, /*gacha_name*/"プレゼントパニック！　ランドソルのサンタたち", /*item_type*/2, /*item_id*/60282, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10030, /*event_id*/10030, /*gacha_name*/"忘却のキャロル", /*item_type*/2, /*item_id*/60292, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10031, /*event_id*/10031, /*gacha_name*/"激走！　ランドソルギルドレース", /*item_type*/2, /*item_id*/60302, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10032, /*event_id*/10032, /*gacha_name*/"新春トゥインクルクライシス！", /*item_type*/2, /*item_id*/60312, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10033, /*event_id*/10033, /*gacha_name*/"魔法少女　二人はミスティ＆ピュアリー", /*item_type*/2, /*item_id*/60322, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10034, /*event_id*/10034, /*gacha_name*/"バトルオブバレンタイン！　想いぶつかるスウィートバトル", /*item_type*/2, /*item_id*/60332, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10035, /*event_id*/10035, /*gacha_name*/"スターライトプリンセス　Re:M@STER！", /*item_type*/2, /*item_id*/60342, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10036, /*event_id*/10036, /*gacha_name*/"スターライトプリンセス　Re:M@STER！", /*item_type*/2, /*item_id*/60342, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10037, /*event_id*/10037, /*gacha_name*/"王都の名探偵　嘆きの追跡者（ストーカー）", /*item_type*/2, /*item_id*/60362, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10038, /*event_id*/10038, /*gacha_name*/"授けの財団と聖なる学舎の異端児", /*item_type*/2, /*item_id*/60372, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10039, /*event_id*/10039, /*gacha_name*/"アストルムに咲く双輪の華", /*item_type*/2, /*item_id*/60382, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10040, /*event_id*/10040, /*gacha_name*/"まきばの四農士　貧乏牧場奮闘記！", /*item_type*/2, /*item_id*/60392, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10041, /*event_id*/10041, /*gacha_name*/"ショーグン道中記　白翼のサムライ", /*item_type*/2, /*item_id*/60402, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10042, /*event_id*/10042, /*gacha_name*/"不思議の国のリノ　小さなアリスと希望の絵本", /*item_type*/2, /*item_id*/60412, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10043, /*event_id*/10043, /*gacha_name*/"スズナレインボーステージ！", /*item_type*/2, /*item_id*/60422, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10044, /*event_id*/10044, /*gacha_name*/"七夕剣客旅情譚　天に流れる夏の恋", /*item_type*/2, /*item_id*/60432, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10045, /*event_id*/10045, /*gacha_name*/"真夏のマホマホ王国 波打ち際のソウルサマー！", /*item_type*/2, /*item_id*/60442, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10046, /*event_id*/10046, /*gacha_name*/"ミサトサマーエール！　夢追う真夏のナイン", /*item_type*/2, /*item_id*/60452, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10047, /*event_id*/10047, /*gacha_name*/"森の臆病者と聖なる学舎の異端児", /*item_type*/2, /*item_id*/60462, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/19003, /*event_id*/10003, /*gacha_name*/"ヴァンパイアハンターwithイリヤ討伐証交換", /*item_type*/2, /*item_id*/60022, /*cost*/1, /*repeat_step*/5);
