CREATE TABLE 'hatsune_description' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'description' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `hatsune_description` VALUES (/*id*/1, /*event_id*/10001, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーは、イベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/2, /*event_id*/10001, /*type*/1, /*description*/"イベントクエストを進めるとボスが登場します。\nボスには、ボスチケットを使うことで挑むことができます。\nボス撃破で、討伐証を大量にゲットできるので、思い切って挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/3, /*event_id*/10001, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/4, /*event_id*/10002, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/5, /*event_id*/10002, /*type*/1, /*description*/"イベントクエストを進めるとボスが登場します。\nボスには、ボスチケットを使うことで挑むことができます。\nボス撃破で討伐証を大量にゲットできるので思い切って挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/6, /*event_id*/10002, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/7, /*event_id*/10003, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/8, /*event_id*/10003, /*type*/1, /*description*/"イベントクエストを進めるとボスが登場します。\nボスには、ボスチケットを使うことで挑むことができます。\nボス撃破で討伐証を大量にゲットできるので思い切って挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/9, /*event_id*/10003, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/10, /*event_id*/10004, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/11, /*event_id*/10004, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/12, /*event_id*/10004, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/13, /*event_id*/10004, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/14, /*event_id*/10005, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/15, /*event_id*/10005, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/16, /*event_id*/10005, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/17, /*event_id*/10005, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/18, /*event_id*/10006, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/19, /*event_id*/10006, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/20, /*event_id*/10006, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/21, /*event_id*/10007, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/22, /*event_id*/10007, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/23, /*event_id*/10007, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/24, /*event_id*/10007, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/25, /*event_id*/10008, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/26, /*event_id*/10008, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/27, /*event_id*/10008, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/28, /*event_id*/10009, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/29, /*event_id*/10009, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/30, /*event_id*/10009, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/31, /*event_id*/10009, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/32, /*event_id*/10010, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/33, /*event_id*/10010, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/34, /*event_id*/10010, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/35, /*event_id*/10010, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/36, /*event_id*/10010, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/37, /*event_id*/10011, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/38, /*event_id*/10011, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/39, /*event_id*/10011, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/40, /*event_id*/10011, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/41, /*event_id*/10011, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/42, /*event_id*/10012, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/43, /*event_id*/10012, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/44, /*event_id*/10012, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/45, /*event_id*/10012, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/46, /*event_id*/10013, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/47, /*event_id*/10013, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/48, /*event_id*/10013, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/49, /*event_id*/10013, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/50, /*event_id*/10013, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/51, /*event_id*/10014, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/52, /*event_id*/10014, /*type*/1, /*description*/"イベントクエストを進めるとボスが登場します。\nボスには、ボスチケットを使うことで挑むことができます。\nボス撃破で討伐証を大量にゲットできるので思い切って挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/53, /*event_id*/10014, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/54, /*event_id*/10014, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/55, /*event_id*/10015, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/56, /*event_id*/10015, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/57, /*event_id*/10015, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/58, /*event_id*/10015, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/59, /*event_id*/10016, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/60, /*event_id*/10016, /*type*/1, /*description*/"イベントクエストを進めるとボスが登場します。\nボスには、ボスチケットを使うことで挑むことができます。\nボス撃破で討伐証を大量にゲットできるので思い切って挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/61, /*event_id*/10016, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/62, /*event_id*/10016, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/63, /*event_id*/10017, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/64, /*event_id*/10017, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/65, /*event_id*/10017, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/66, /*event_id*/10017, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/67, /*event_id*/10017, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。\n期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/68, /*event_id*/10017, /*type*/3, /*description*/"エキシビションモードは、SPECIALのボスと何度も戦えます。\nまた、バトルのログを保存して振り返ることができるので、\n独自の攻略法を見つけたり、様々な編成を試してみましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/69, /*event_id*/10017, /*type*/4, /*description*/"イベントクエストやボスに挑戦すると、信頼度エピソードが発生する　　ことがございます。会話の結果によって信頼度がアップし、　　　　　　特定の信頼度に到達するとプレゼントがもらえます。");
INSERT INTO `hatsune_description` VALUES (/*id*/70, /*event_id*/10018, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/71, /*event_id*/10018, /*type*/1, /*description*/"イベントクエストを進めるとボスが登場します。\nボスには、ボスチケットを使うことで挑むことができます。\nボス撃破で討伐証を大量にゲットできるので思い切って挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/72, /*event_id*/10018, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/73, /*event_id*/10018, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001901, /*event_id*/10019, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001902, /*event_id*/10019, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001903, /*event_id*/10019, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001904, /*event_id*/10019, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001905, /*event_id*/10019, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001906, /*event_id*/10019, /*type*/4, /*description*/"イベントクエストやボスに挑戦すると、信頼度エピソードが発生する\nことがございます。会話の結果によって信頼度がアップし、\n特定の信頼度に到達するとプレゼントがもらえます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002001, /*event_id*/10020, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002002, /*event_id*/10020, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002003, /*event_id*/10020, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002004, /*event_id*/10020, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002201, /*event_id*/10022, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002202, /*event_id*/10022, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002203, /*event_id*/10022, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002204, /*event_id*/10022, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002301, /*event_id*/10023, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002302, /*event_id*/10023, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002303, /*event_id*/10023, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002304, /*event_id*/10023, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。\n期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002305, /*event_id*/10023, /*type*/4, /*description*/"イベントクエストやボスに挑戦すると、信頼度エピソードが発生する\nことがございます。会話の結果によって信頼度がアップし、\n特定の信頼度に到達するとプレゼントがもらえます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002306, /*event_id*/10023, /*type*/5, /*description*/"聖テレサ女学院の短期編入を終えた\nアオイのもとに『なかよし部』の\n３人から便りが届いた......");
INSERT INTO `hatsune_description` VALUES (/*id*/1002401, /*event_id*/10024, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002402, /*event_id*/10024, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002403, /*event_id*/10024, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002501, /*event_id*/10025, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002502, /*event_id*/10025, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002503, /*event_id*/10025, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002504, /*event_id*/10025, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002505, /*event_id*/10025, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。\n期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002506, /*event_id*/10025, /*type*/3, /*description*/"エキシビションモードは、SPECIALのボスと何度も戦えます。\nまた、バトルのログを保存して振り返ることができるので、\n独自の攻略法を見つけたり、様々な編成を試してみましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002507, /*event_id*/10025, /*type*/4, /*description*/"イベントクエストやボスに挑戦すると、信頼度エピソードが発生する\nことがございます。会話の結果によって信頼度がアップし、\n特定の信頼度に到達するとプレゼントがもらえます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002601, /*event_id*/10026, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002602, /*event_id*/10026, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002603, /*event_id*/10026, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002604, /*event_id*/10026, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002701, /*event_id*/10027, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002702, /*event_id*/10027, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002703, /*event_id*/10027, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002704, /*event_id*/10027, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。\n期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002705, /*event_id*/10027, /*type*/3, /*description*/"エキシビションモードは、SPECIALのボスと何度も戦えます。\nまた、バトルのログを保存して振り返ることができるので、\n独自の攻略法を見つけたり、様々な編成を試してみましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002706, /*event_id*/10027, /*type*/4, /*description*/"イベントクエストやボスに挑戦すると、信頼度エピソードが発生する\nことがございます。会話の結果によって信頼度がアップし、\n特定の信頼度に到達するとプレゼントがもらえます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002801, /*event_id*/10028, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002802, /*event_id*/10028, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002803, /*event_id*/10028, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002901, /*event_id*/10029, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002902, /*event_id*/10029, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002903, /*event_id*/10029, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002904, /*event_id*/10029, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002905, /*event_id*/10029, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。\n期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002906, /*event_id*/10029, /*type*/3, /*description*/"エキシビションモードは、SPECIALのボスと何度も戦えます。\nまた、バトルのログを保存して振り返ることができるので、\n独自の攻略法を見つけたり、様々な編成を試してみましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002907, /*event_id*/10029, /*type*/4, /*description*/"イベントクエストやボスに挑戦すると、信頼度エピソードが発生する\nことがございます。会話の結果によって信頼度がアップし、\n特定の信頼度に到達するとプレゼントがもらえます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003001, /*event_id*/10030, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003002, /*event_id*/10030, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003003, /*event_id*/10030, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003004, /*event_id*/10030, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003101, /*event_id*/10031, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003102, /*event_id*/10031, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003103, /*event_id*/10031, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003104, /*event_id*/10031, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003105, /*event_id*/10031, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。\n期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003106, /*event_id*/10031, /*type*/3, /*description*/"エキシビションモードは、SPECIALのボスと何度も戦えます。\nまた、バトルのログを保存して振り返ることができるので、\n独自の攻略法を見つけたり、様々な編成を試してみましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003201, /*event_id*/10032, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003202, /*event_id*/10032, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003203, /*event_id*/10032, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003204, /*event_id*/10032, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003301, /*event_id*/10033, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003302, /*event_id*/10033, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003303, /*event_id*/10033, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003304, /*event_id*/10033, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003305, /*event_id*/10033, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。\n期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003306, /*event_id*/10033, /*type*/3, /*description*/"エキシビションモードは、SPECIALのボスと何度も戦えます。\nまた、バトルのログを保存して振り返ることができるので、\n独自の攻略法を見つけたり、様々な編成を試してみましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003307, /*event_id*/10033, /*type*/4, /*description*/"イベントクエストやボスに挑戦すると、信頼度エピソードが発生する\nことがございます。会話の結果によって信頼度がアップし、\n特定の信頼度に到達するとプレゼントがもらえます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003401, /*event_id*/10034, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003402, /*event_id*/10034, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003403, /*event_id*/10034, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003404, /*event_id*/10034, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003405, /*event_id*/10034, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003406, /*event_id*/10034, /*type*/3, /*description*/"エキシビションモードは、SPECIALのボスと何度も戦えます。\nまた、バトルのログを保存して振り返ることができるので、\n独自の攻略法を見つけたり、様々な編成を試してみましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003501, /*event_id*/10035, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003502, /*event_id*/10035, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003503, /*event_id*/10035, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003504, /*event_id*/10035, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003505, /*event_id*/10035, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。\n期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003506, /*event_id*/10035, /*type*/3, /*description*/"エキシビションモードは、SPECIALのボスと何度も戦えます。\nまた、バトルのログを保存して振り返ることができるので、\n独自の攻略法を見つけたり、様々な編成を試してみましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003601, /*event_id*/10036, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003602, /*event_id*/10036, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003603, /*event_id*/10036, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003604, /*event_id*/10036, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003605, /*event_id*/10036, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。\n期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003606, /*event_id*/10036, /*type*/3, /*description*/"エキシビションモードは、SPECIALのボスと何度も戦えます。\nまた、バトルのログを保存して振り返ることができるので、\n独自の攻略法を見つけたり、様々な編成を試してみましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003701, /*event_id*/10037, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003702, /*event_id*/10037, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003703, /*event_id*/10037, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003704, /*event_id*/10037, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003705, /*event_id*/10037, /*type*/3, /*description*/"エキシビションモードは、SPECIALのボスと何度も戦えます。\nまた、バトルのログを保存して振り返ることができるので、\n独自の攻略法を見つけたり、様々な編成を試してみましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/100210105, /*event_id*/10021, /*type*/1, /*description*/"イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `hatsune_description` VALUES (/*id*/100210106, /*event_id*/10021, /*type*/1, /*description*/"イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/100210107, /*event_id*/10021, /*type*/1, /*description*/"強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/100210108, /*event_id*/10021, /*type*/1, /*description*/"討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/100210309, /*event_id*/10021, /*type*/3, /*description*/"スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802001, /*event_id*/10008, /*type*/2, /*description*/"働き口を求め、渓谷の洞窟へと向かうアンナ。\n古文書目当てに、仕入れ先へと向かうナナカ。\n村人の願いを聞き入れ、村へと向かうルカ。\n3人は各々の目的地へと出発するのだった。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802002, /*event_id*/10008, /*type*/2, /*description*/"村で悪党を鮮やかに成敗したルカ。\n報復に怯える村人との会話の中で、\n彼女は渓谷一帯で暗躍する巨悪の存在に勘付く。\n一方、渓谷の洞窟へと向かったアンナは……");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802003, /*event_id*/10008, /*type*/2, /*description*/"渓谷の洞窟で働き始めたアンナたちだったが、\nそこは事前の話とは違い、無法者がはびこり、\n過酷な労働が支配する劣悪な環境だった。\nそのころ、仕入先へと向かったナナカは……");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802004, /*event_id*/10008, /*type*/2, /*description*/"とある貴族に古文書を独占されてしまい、\n仕入の目的を果たすことができなかったナナカ。\n帰る道すがら悪党に襲われた彼女は、\nルカと合流するべく村への道を急ぐのだった……");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802005, /*event_id*/10008, /*type*/2, /*description*/"渓谷の洞窟が悪党の本拠地であることを知り、\nアンナたちとの合流を目指すルカとナナカ。\n辛くも脱出したアンナたちを救出し、\n一同はひとまず洞窟から退くことにする。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001002001, /*event_id*/10010, /*type*/2, /*description*/"願いを奉じ、浄化する神殿。ここでは、\n成就しなかった「具現化した願い」が人を襲うので\nユイたちに警備の依頼がきていた。\n報酬からお年玉を渡すため警備に参加する。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001002002, /*event_id*/10010, /*type*/2, /*description*/"参拝客で慌ただしくなるも、困っているみんなで\n助け合ってもらいつつ、仕事をこなしていく一同。\nそこに、親を探す「具現化した願い」が現れるが、\n親として優しく接するヒヨリたちに浄化された。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001002003, /*event_id*/10010, /*type*/2, /*description*/"仕事に慣れてきた一同だが、そこに彼女とキスを\nする方法を知りたい「具現化した願い」が現れる。\nだが、体勢を崩したユイをかばい、キスする寸前の\n主人公たちの姿を見て浄化した。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001002004, /*event_id*/10010, /*type*/2, /*description*/"夜が近づき、参拝客も増えて忙しさが増す一同。\nそこに「具現化した願い」が現れる。\n元気づけてほしいと嘆き彷徨うが、\nレイの「必死」な応援で浄化するのであった。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001002005, /*event_id*/10010, /*type*/2, /*description*/"多くの願いを浄化し、一度休憩を入れる一同。\nその時、願いが最も濃くなるという\n年末までの数時間が訪れ、願いが次々と具現化。\n暴走した願いは、黒い霧となって神殿を覆った。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001702001, /*event_id*/10017, /*type*/2, /*description*/"ペテルギウスを名乗る男に襲われる【美食殿】一行。\n間一髪で魔女教大罪司教である彼を撃退し、\n【美食殿】と仲を深めたエミリアたちは\n【サレンディア救護院】に身を置くことになる。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001702002, /*event_id*/10017, /*type*/2, /*description*/"大罪司教ペテルギウスの暗躍に王宮の騎士団が動き\n副団長のクリスティーナがとある村へと派遣される。\n大罪司教の動きをキャルから知らされた一行は\nその謎の能力を危険視し現場へ向かうのだった。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001702003, /*event_id*/10017, /*type*/2, /*description*/"苦戦するクリスティーナの元へ駆けつけた一行。\n有利かと思われた形勢は魔女教徒の出現で一転する。\nエミリアたちを加えた【美食殿】は魔法の氷塊で\nペテルギウスを孤立させ、最終決戦に挑む！");
INSERT INTO `hatsune_description` VALUES (/*id*/1002802001, /*event_id*/10028, /*type*/2, /*description*/"働き口を求め、渓谷の洞窟へと向かうアンナ。\n古文書目当てに、仕入れ先へと向かうナナカ。\n村人の願いを聞き入れ、村へと向かうルカ。\n3人は各々の目的地へと出発するのだった。");
INSERT INTO `hatsune_description` VALUES (/*id*/1002802002, /*event_id*/10028, /*type*/2, /*description*/"村で悪党を鮮やかに成敗したルカ。\n報復に怯える村人との会話の中で、\n彼女は渓谷一帯で暗躍する巨悪の存在に勘付く。\n一方、渓谷の洞窟へと向かったアンナは……");
INSERT INTO `hatsune_description` VALUES (/*id*/1002802003, /*event_id*/10028, /*type*/2, /*description*/"渓谷の洞窟で働き始めたアンナたちだったが、\nそこは事前の話とは違い、無法者がはびこり、\n過酷な労働が支配する劣悪な環境だった。\nそのころ、仕入先へと向かったナナカは……");
INSERT INTO `hatsune_description` VALUES (/*id*/1002802004, /*event_id*/10028, /*type*/2, /*description*/"とある貴族に古文書を独占されてしまい、\n仕入の目的を果たすことができなかったナナカ。\n帰る道すがら悪党に襲われた彼女は、\nルカと合流するべく村への道を急ぐのだった……");
INSERT INTO `hatsune_description` VALUES (/*id*/1002802005, /*event_id*/10028, /*type*/2, /*description*/"渓谷の洞窟が悪党の本拠地であることを知り、\nアンナたちとの合流を目指すルカとナナカ。\n辛くも脱出したアンナたちを救出し、\n一同はひとまず洞窟から退くことにする。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003202001, /*event_id*/10032, /*type*/2, /*description*/"願いを奉じ、浄化する神殿。ここでは、\n成就しなかった「具現化した願い」が人を襲うので\nユイたちに警備の依頼がきていた。\n報酬からお年玉を渡すため警備に参加する。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003202002, /*event_id*/10032, /*type*/2, /*description*/"参拝客で慌ただしくなるも、困っているみんなで\n助け合ってもらいつつ、仕事をこなしていく一同。\nそこに、親を探す「具現化した願い」が現れるが、\n親として優しく接するヒヨリたちに浄化された。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003202003, /*event_id*/10032, /*type*/2, /*description*/"仕事に慣れてきた一同だが、そこに彼女とキスを\nする方法を知りたい「具現化した願い」が現れる。\nだが、体勢を崩したユイをかばい、キスする寸前の\n主人公たちの姿を見て浄化した。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003202004, /*event_id*/10032, /*type*/2, /*description*/"夜が近づき、参拝客も増えて忙しさが増す一同。\nそこに「具現化した願い」が現れる。\n元気づけてほしいと嘆き彷徨うが、\nレイの「必死」な応援で浄化するのであった。");
INSERT INTO `hatsune_description` VALUES (/*id*/1003202005, /*event_id*/10032, /*type*/2, /*description*/"多くの願いを浄化し、一度休憩を入れる一同。\nその時、願いが最も濃くなるという\n年末までの数時間が訪れ、願いが次々と具現化。\n暴走した願いは、黒い霧となって神殿を覆った。");
CREATE INDEX 'hatsune_description_0_event_id_1_type' on 'hatsune_description'('event_id','type');
