CREATE TABLE 'hatsune_limit_chara' ('event_boss_id' INTEGER NOT NULL, 'limit_chara_type_1' INTEGER NOT NULL, PRIMARY KEY('event_boss_id'));
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1008401, /*limit_chara_type_1*/58);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1008402, /*limit_chara_type_1*/58);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1008403, /*limit_chara_type_1*/58);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1008404, /*limit_chara_type_1*/58);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1008405, /*limit_chara_type_1*/58);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1011201, /*limit_chara_type_1*/58);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1011202, /*limit_chara_type_1*/58);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1011203, /*limit_chara_type_1*/58);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1011204, /*limit_chara_type_1*/58);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1011205, /*limit_chara_type_1*/58);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1013001, /*limit_chara_type_1*/182);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1013002, /*limit_chara_type_1*/182);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1013003, /*limit_chara_type_1*/182);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1013004, /*limit_chara_type_1*/182);
INSERT INTO `hatsune_limit_chara` VALUES (/*event_boss_id*/1013005, /*limit_chara_type_1*/182);
