CREATE TABLE 'love_chara' ('love_level' INTEGER NOT NULL, 'total_love' INTEGER NOT NULL, 'unlocked_class' INTEGER NOT NULL, 'rarity' INTEGER NOT NULL, PRIMARY KEY('love_level'));
INSERT INTO `love_chara` VALUES (/*love_level*/1, /*total_love*/0, /*unlocked_class*/1, /*rarity*/1);
INSERT INTO `love_chara` VALUES (/*love_level*/2, /*total_love*/175, /*unlocked_class*/1, /*rarity*/1);
INSERT INTO `love_chara` VALUES (/*love_level*/3, /*total_love*/420, /*unlocked_class*/1, /*rarity*/1);
INSERT INTO `love_chara` VALUES (/*love_level*/4, /*total_love*/700, /*unlocked_class*/1, /*rarity*/1);
INSERT INTO `love_chara` VALUES (/*love_level*/5, /*total_love*/1400, /*unlocked_class*/1, /*rarity*/3);
INSERT INTO `love_chara` VALUES (/*love_level*/6, /*total_love*/2100, /*unlocked_class*/1, /*rarity*/3);
INSERT INTO `love_chara` VALUES (/*love_level*/7, /*total_love*/2800, /*unlocked_class*/1, /*rarity*/3);
INSERT INTO `love_chara` VALUES (/*love_level*/8, /*total_love*/4200, /*unlocked_class*/1, /*rarity*/3);
INSERT INTO `love_chara` VALUES (/*love_level*/9, /*total_love*/6300, /*unlocked_class*/1, /*rarity*/6);
INSERT INTO `love_chara` VALUES (/*love_level*/10, /*total_love*/9100, /*unlocked_class*/1, /*rarity*/6);
INSERT INTO `love_chara` VALUES (/*love_level*/11, /*total_love*/12600, /*unlocked_class*/1, /*rarity*/6);
INSERT INTO `love_chara` VALUES (/*love_level*/12, /*total_love*/16800, /*unlocked_class*/1, /*rarity*/6);
