CREATE TABLE 'room_effect' ('id' INTEGER NOT NULL, 'reward_get' INTEGER NOT NULL, 'jukebox' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `room_effect` VALUES (/*id*/1, /*reward_get*/1, /*jukebox*/0);
INSERT INTO `room_effect` VALUES (/*id*/2, /*reward_get*/2, /*jukebox*/0);
INSERT INTO `room_effect` VALUES (/*id*/3, /*reward_get*/3, /*jukebox*/0);
INSERT INTO `room_effect` VALUES (/*id*/4, /*reward_get*/4, /*jukebox*/0);
INSERT INTO `room_effect` VALUES (/*id*/5, /*reward_get*/5, /*jukebox*/0);
INSERT INTO `room_effect` VALUES (/*id*/6, /*reward_get*/6, /*jukebox*/0);
INSERT INTO `room_effect` VALUES (/*id*/7, /*reward_get*/7, /*jukebox*/0);
INSERT INTO `room_effect` VALUES (/*id*/8, /*reward_get*/8, /*jukebox*/0);
INSERT INTO `room_effect` VALUES (/*id*/9, /*reward_get*/0, /*jukebox*/1);
