CREATE TABLE 'shiori_description' ('id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'description' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `shiori_description` VALUES (/*id*/101, /*type*/1, /*description*/"サイドストーリーでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。");
INSERT INTO `shiori_description` VALUES (/*id*/201, /*type*/2, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/301, /*type*/3, /*description*/"ボスに挑戦すると、信頼度エピソードが発生する\nことがございます。会話の結果によって信頼度がアップし、\n特定の信頼度に到達するとプレゼントがもらえます。");
INSERT INTO `shiori_description` VALUES (/*id*/20005, /*type*/4, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20007, /*type*/5, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20009, /*type*/6, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20010, /*type*/7, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20011, /*type*/8, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20013, /*type*/9, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20015, /*type*/10, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20016, /*type*/11, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20018, /*type*/12, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20020, /*type*/13, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20021, /*type*/14, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20022, /*type*/15, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20025, /*type*/16, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20026, /*type*/17, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20027, /*type*/18, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
INSERT INTO `shiori_description` VALUES (/*id*/20029, /*type*/19, /*description*/"ミッションを達成すると解放できるキャラが登場します。\nミッションクリアを目指しましょう。");
CREATE INDEX 'shiori_description_0_type' on 'shiori_description'('type');
