CREATE TABLE sqlite_stat1(tbl,idx,stat);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_navi_comment_condition", /*idx*/"", /*stat*/12);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_gacha_data", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_boss_treasure_content", /*idx*/"", /*stat*/24);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_boss_treasure_box", /*idx*/"", /*stat*/6);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_map", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"stamp", /*idx*/"", /*stat*/32);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_freegacha_data", /*idx*/"", /*stat*/2);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_schedule", /*idx*/"", /*stat*/30);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_cost_group", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quest", /*idx*/"", /*stat*/60);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_fix_reward", /*idx*/"", /*stat*/40);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"odds_name_data", /*idx*/"", /*stat*/9);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_daily_rank_reward", /*idx*/"", /*stat*/40);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"album_production_list", /*idx*/"", /*stat*/400);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"still", /*idx*/"", /*stat*/194);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"movie", /*idx*/"", /*stat*/46);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_effect_reward_get", /*idx*/"sqlite_autoindex_room_effect_reward_get_1", /*stat*/"44 6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_enemy_reward_group", /*idx*/"", /*stat*/137);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quest_condition", /*idx*/"", /*stat*/60);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_defence_reward", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_emotion_icon", /*idx*/"", /*stat*/18);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dungeon_quest_data", /*idx*/"", /*stat*/30);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_formation", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"album_voice_list", /*idx*/"", /*stat*/3182);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_unit_comments", /*idx*/"room_unit_comments_0_unit_id", /*stat*/"2199 24");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_unit_comments", /*idx*/"sqlite_autoindex_room_unit_comments_1", /*stat*/"2199 24 8 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_freegacha", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_announcement", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_setup", /*idx*/"", /*stat*/147);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_description", /*idx*/"", /*stat*/9);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item", /*idx*/"", /*stat*/185);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_grade", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_motion_list", /*idx*/"", /*stat*/50);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_schedule", /*idx*/"", /*stat*/6);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"guild", /*idx*/"", /*stat*/15);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_enemy_parameter", /*idx*/"", /*stat*/3233);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_stationary_mission_data", /*idx*/"", /*stat*/90);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shop_static_price_group", /*idx*/"", /*stat*/5);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_map_data", /*idx*/"", /*stat*/8);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_invite_level_group", /*idx*/"", /*stat*/19);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_scenario", /*idx*/"room_chat_scenario_0_id", /*stat*/"262 15");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_scenario", /*idx*/"sqlite_autoindex_room_chat_scenario_1", /*stat*/"262 15 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_background", /*idx*/"", /*stat*/58);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dungeon_area_data", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_status_coefficient", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_navi_comment", /*idx*/"", /*stat*/33);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"navi_comment", /*idx*/"", /*stat*/18);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_unit_condition", /*idx*/"", /*stat*/50);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_wave_group_data", /*idx*/"", /*stat*/3798);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_unlock_story_condition", /*idx*/"", /*stat*/24);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_effect", /*idx*/"", /*stat*/8);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_promotion_status", /*idx*/"sqlite_autoindex_unit_promotion_status_1", /*stat*/"424 8 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_rarity", /*idx*/"sqlite_autoindex_unit_rarity_1", /*stat*/"325 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_mission_reward_data", /*idx*/"", /*stat*/156);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_enemy_data", /*idx*/"", /*stat*/157);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"goldset_data_teamlevel", /*idx*/"", /*stat*/110);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_data", /*idx*/"", /*stat*/79);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_comments", /*idx*/"unit_comments_0_unit_id_1_use_type", /*stat*/"500 5 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_comments", /*idx*/"unit_comments_0_unit_id", /*stat*/"500 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_boss_condition", /*idx*/"", /*stat*/6);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_attack_pattern", /*idx*/"", /*stat*/278);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_story_detail", /*idx*/"", /*stat*/24);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_character_personality", /*idx*/"", /*stat*/50);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_change", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"position_setting", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_story_status", /*idx*/"", /*stat*/350);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"bg_data", /*idx*/"sqlite_autoindex_bg_data_1", /*stat*/"67 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period_rank_reward", /*idx*/"", /*stat*/39);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_data", /*idx*/"", /*stat*/77);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_daily_mission_data", /*idx*/"", /*stat*/6);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_schedule", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"content_release_data", /*idx*/"", /*stat*/21);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_release_data", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_promotion", /*idx*/"sqlite_autoindex_unit_promotion_1", /*stat*/"630 9 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"character_love_rankup_text", /*idx*/"", /*stat*/42);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_max_rank_reward", /*idx*/"", /*stat*/79);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"training_quest_data", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_profile", /*idx*/"", /*stat*/58);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tips", /*idx*/"", /*stat*/50);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_enhance_rate", /*idx*/"", /*stat*/152);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_daily_rank_reward", /*idx*/"", /*stat*/40);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"stationary_mission_data", /*idx*/"", /*stat*/302);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_donation", /*idx*/"", /*stat*/9);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"goldset_data", /*idx*/"", /*stat*/70);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_story_data", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_data", /*idx*/"", /*stat*/205);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_group", /*idx*/"clan_battle_boss_group_0_clan_battle_boss_group_id", /*stat*/"40 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_group", /*idx*/"sqlite_autoindex_clan_battle_boss_group_1", /*stat*/"40 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_max_rank_reward", /*idx*/"", /*stat*/79);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_quest_data", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"enemy_reward_data", /*idx*/"", /*stat*/720);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_odds_data", /*idx*/"clan_battle_odds_data_0_odds_group_id", /*stat*/"12 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_odds_data", /*idx*/"sqlite_autoindex_clan_battle_odds_data_1", /*stat*/"12 3 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period", /*idx*/"clan_battle_period_0_clan_battle_id", /*stat*/"4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period", /*idx*/"sqlite_autoindex_clan_battle_period_1", /*stat*/"4 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_defeat_notice", /*idx*/"", /*stat*/6);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_boss", /*idx*/"", /*stat*/6);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gift_message", /*idx*/"", /*stat*/45);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"enemy_parameter", /*idx*/"", /*stat*/1620);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"experience_team", /*idx*/"", /*stat*/99);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_enhance_data", /*idx*/"sqlite_autoindex_equipment_enhance_data_1", /*stat*/"14 4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_item", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"banner", /*idx*/"", /*stat*/15);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"worldmap", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_data", /*idx*/"", /*stat*/26);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_detail", /*idx*/"sqlite_autoindex_room_item_detail_1", /*stat*/"221 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_introduction", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_skill_data", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ailment_data", /*idx*/"", /*stat*/18);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_area_data", /*idx*/"", /*stat*/26);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_bg_data", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_craft", /*idx*/"", /*stat*/114);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"mission_reward_data", /*idx*/"", /*stat*/78);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_reward_data", /*idx*/"", /*stat*/302);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_info", /*idx*/"", /*stat*/17);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_skill_data", /*idx*/"", /*stat*/221);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skip_monster_data", /*idx*/"", /*stat*/275);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"experience_unit", /*idx*/"", /*stat*/99);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"reward_collect_guide", /*idx*/"", /*stat*/323);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_defence_reward", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"love_chara", /*idx*/"", /*stat*/12);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"actual_unit_background", /*idx*/"", /*stat*/50);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_data", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_character_mask", /*idx*/"", /*stat*/226);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"item_data", /*idx*/"", /*stat*/77);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_data", /*idx*/"", /*stat*/517);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_action", /*idx*/"", /*stat*/751);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"daily_mission_data", /*idx*/"", /*stat*/15);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"cooperation_quest_data", /*idx*/"", /*stat*/6);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quest_area", /*idx*/"", /*stat*/6);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_detail", /*idx*/"login_bonus_detail_0_login_bonus_id_1_count", /*stat*/"26 9 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_introduction", /*idx*/"", /*stat*/9);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_data", /*idx*/"", /*stat*/265);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_condition_data", /*idx*/"", /*stat*/205);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_damage_rank", /*idx*/"clan_battle_boss_damage_rank_0_damage_rank_id", /*stat*/"160 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_damage_rank", /*idx*/"sqlite_autoindex_clan_battle_boss_damage_rank_1", /*stat*/"160 4 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_data", /*idx*/"", /*stat*/20);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_identity", /*idx*/"", /*stat*/50);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"wave_group_data", /*idx*/"", /*stat*/737);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"season_pack", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_cost", /*idx*/"", /*stat*/98);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_mypage_pos", /*idx*/"", /*stat*/36);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"resist_data", /*idx*/"", /*stat*/17);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_detail", /*idx*/"", /*stat*/504);
CREATE INDEX 'unit_comments_0_unit_id' on 'unit_comments'('unit_id')CREATE INDEX 'unit_comments_0_unit_id_1_use_type' on 'unit_comments'('unit_id','use_type')CREATE INDEX 'login_bonus_detail_0_login_bonus_id_1_count' on 'login_bonus_detail'('login_bonus_id','count')CREATE INDEX 'room_unit_comments_0_unit_id' on 'room_unit_comments'('unit_id')CREATE INDEX 'room_chat_scenario_0_id' on 'room_chat_scenario'('id')CREATE INDEX 'clan_battle_period_0_clan_battle_id' on 'clan_battle_period'('clan_battle_id')CREATE INDEX 'clan_battle_boss_group_0_clan_battle_boss_group_id' on 'clan_battle_boss_group'('clan_battle_boss_group_id')CREATE INDEX 'clan_battle_boss_damage_rank_0_damage_rank_id' on 'clan_battle_boss_damage_rank'('damage_rank_id')CREATE INDEX 'clan_battle_odds_data_0_odds_group_id' on 'clan_battle_odds_data'('odds_group_id')CREATE INDEX 'clan_battle_period_rank_bonus_0_ranking_bonus_group_id' on 'clan_battle_period_rank_bonus'('ranking_bonus_group_id')