CREATE TABLE 'unit_background' ('unit_id' INTEGER NOT NULL, 'unit_name' TEXT NOT NULL, 'bg_id' INTEGER NOT NULL, 'bg_name' TEXT NOT NULL, 'position' REAL NOT NULL, 'face_type' INTEGER NOT NULL, PRIMARY KEY('unit_id'));
INSERT INTO `unit_background` VALUES (/*unit_id*/100101, /*unit_name*/"春咲 ひより", /*bg_id*/500040, /*bg_name*/"ランドソル ギルドハウス", /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/100201, /*unit_name*/"草野 優衣", /*bg_id*/500040, /*bg_name*/"ランドソル ギルドハウス", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100301, /*unit_name*/"士条 怜", /*bg_id*/500040, /*bg_name*/"ランドソル ギルドハウス", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/100401, /*unit_name*/"穂高 みそぎ", /*bg_id*/500140, /*bg_name*/"プラノ平原", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100501, /*unit_name*/"織原 茉莉", /*bg_id*/500090, /*bg_name*/"ランドソル 王城入口", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100601, /*unit_name*/"風宮 あかり", /*bg_id*/500260, /*bg_name*/"古城", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100701, /*unit_name*/"出雲 宮子", /*bg_id*/500260, /*bg_name*/"古城", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100801, /*unit_name*/"虹村 雪", /*bg_id*/500140, /*bg_name*/"プラノ平原", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100901, /*unit_name*/"柊杏奈", /*bg_id*/500050, /*bg_name*/"ランドソル 飲食店内", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/101001, /*unit_name*/"姫宮 真歩", /*bg_id*/500060, /*bg_name*/"自警団 拠点", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101101, /*unit_name*/"衣之咲 璃乃", /*bg_id*/500030, /*bg_name*/"ランドソル 繁華街", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101201, /*unit_name*/"柏崎 初音", /*bg_id*/500180, /*bg_name*/"エルフの森", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/101301, /*unit_name*/"丹野 七々香", /*bg_id*/500050, /*bg_name*/"ランドソル 飲食店内", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/101401, /*unit_name*/"霧原 かすみ", /*bg_id*/500060, /*bg_name*/"自警団 拠点", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101501, /*unit_name*/"愛川 美里", /*bg_id*/500180, /*bg_name*/"エルフの森", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101601, /*unit_name*/"美波 鈴奈", /*bg_id*/500080, /*bg_name*/"ルーセント学院", /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/101701, /*unit_name*/"喜屋武 香織", /*bg_id*/500060, /*bg_name*/"自警団 拠点", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101801, /*unit_name*/"支倉 伊緒", /*bg_id*/500080, /*bg_name*/"ルーセント学院", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102001, /*unit_name*/"茜 ミミ", /*bg_id*/500140, /*bg_name*/"プラノ平原", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/102101, /*unit_name*/"栗林 くるみ", /*bg_id*/500110, /*bg_name*/"サレンディア救護院 広間", /*position*/0.0, /*face_type*/5);
INSERT INTO `unit_background` VALUES (/*unit_id*/102201, /*unit_name*/"風宮 より", /*bg_id*/500260, /*bg_name*/"古城", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102301, /*unit_name*/"北条 綾音", /*bg_id*/500110, /*bg_name*/"サレンディア救護院 広間", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102501, /*unit_name*/"天野 すずめ", /*bg_id*/500110, /*bg_name*/"サレンディア救護院 広間", /*position*/0.0, /*face_type*/10);
INSERT INTO `unit_background` VALUES (/*unit_id*/102601, /*unit_name*/"森近 鈴", /*bg_id*/500150, /*bg_name*/"牧場 拠点", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/102701, /*unit_name*/"倉石 恵理子", /*bg_id*/500050, /*bg_name*/"ランドソル 飲食店内", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102801, /*unit_name*/"佐々木 咲恋", /*bg_id*/500110, /*bg_name*/"サレンディア救護院 広間", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102901, /*unit_name*/"桜井 望", /*bg_id*/500010, /*bg_name*/"ランドソル 市街地", /*position*/0.0, /*face_type*/1);
INSERT INTO `unit_background` VALUES (/*unit_id*/103001, /*unit_name*/"ニノン・ジュベール", /*bg_id*/500140, /*bg_name*/"プラノ平原", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103101, /*unit_name*/"上喜 しのぶ", /*bg_id*/500260, /*bg_name*/"古城", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103201, /*unit_name*/"藤堂 秋乃", /*bg_id*/500070, /*bg_name*/"メルクリウス財団 拠点", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103301, /*unit_name*/"野戸まひる", /*bg_id*/500150, /*bg_name*/"牧場 拠点", /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/103401, /*unit_name*/"綾瀬 ゆかり", /*bg_id*/500070, /*bg_name*/"メルクリウス財団 拠点", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103601, /*unit_name*/"氷川 鏡華", /*bg_id*/500140, /*bg_name*/"プラノ平原", /*position*/0.0, /*face_type*/1);
INSERT INTO `unit_background` VALUES (/*unit_id*/103701, /*unit_name*/"御久間 智", /*bg_id*/500090, /*bg_name*/"ランドソル 王城入口", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/103801, /*unit_name*/"柏崎 栞", /*bg_id*/500150, /*bg_name*/"牧場 拠点", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104001, /*unit_name*/"双葉 碧", /*bg_id*/500180, /*bg_name*/"エルフの森", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104201, /*unit_name*/"三角 千歌", /*bg_id*/500010, /*bg_name*/"ランドソル 市街地", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/104301, /*unit_name*/"安芸 真琴", /*bg_id*/500060, /*bg_name*/"自警団 拠点", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104401, /*unit_name*/"イリヤ・オーンスタイン", /*bg_id*/500260, /*bg_name*/"古城", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/104501, /*unit_name*/"遠見 空花", /*bg_id*/500140, /*bg_name*/"プラノ平原", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/104601, /*unit_name*/"宮坂たまき", /*bg_id*/500070, /*bg_name*/"メルクリウス財団 拠点", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/104701, /*unit_name*/"白銀 純", /*bg_id*/500090, /*bg_name*/"ランドソル 王城入口", /*position*/0.0, /*face_type*/1);
INSERT INTO `unit_background` VALUES (/*unit_id*/104801, /*unit_name*/"大神 美冬", /*bg_id*/500070, /*bg_name*/"メルクリウス財団 拠点", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104901, /*unit_name*/"星野静流", /*bg_id*/500030, /*bg_name*/"ランドソル 繁華街", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/105001, /*unit_name*/"玉泉美咲", /*bg_id*/500080, /*bg_name*/"ルーセント学院", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/105101, /*unit_name*/"宵ヶ浜 深月", /*bg_id*/500050, /*bg_name*/"ランドソル 飲食店内", /*position*/0.0, /*face_type*/6);
INSERT INTO `unit_background` VALUES (/*unit_id*/105201, /*unit_name*/"リマ", /*bg_id*/500150, /*bg_name*/"牧場 拠点", /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/105301, /*unit_name*/"モニカ・ヴァイスヴィント", /*bg_id*/500140, /*bg_name*/"プラノ平原", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/105401, /*unit_name*/"繭宮つむぎ", /*bg_id*/500010, /*bg_name*/"ランドソル 市街地", /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/105501, /*unit_name*/"石橋あゆみ", /*bg_id*/500140, /*bg_name*/"プラノ平原", /*position*/0.0, /*face_type*/15);
INSERT INTO `unit_background` VALUES (/*unit_id*/105601, /*unit_name*/"太刀洗流夏", /*bg_id*/500050, /*bg_name*/"ランドソル 飲食店内", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/105701, /*unit_name*/"ジータ", /*bg_id*/500200, /*bg_name*/"ブリザ渓谷", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/105801, /*unit_name*/"ペコリーヌ", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/105901, /*unit_name*/"コッコロ", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/106001, /*unit_name*/"キャル", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/106101, /*unit_name*/"ムイミ", /*bg_id*/500341, /*bg_name*/"ラビリンスギルド拠点", /*position*/0.0, /*face_type*/20);
INSERT INTO `unit_background` VALUES (/*unit_id*/106301, /*unit_name*/"アリサ", /*bg_id*/500170, /*bg_name*/"ミステリオン森林", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/106401, /*unit_name*/"シェフィ", /*bg_id*/500361, /*bg_name*/"美食殿 ギルドハウス", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/106501, /*unit_name*/"カヤ", /*bg_id*/500833, /*bg_name*/"密林_テント", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/106601, /*unit_name*/"イノリ", /*bg_id*/500833, /*bg_name*/"密林_テント", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/106701, /*unit_name*/"ホマレ", /*bg_id*/500833, /*bg_name*/"密林_テント", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/106801, /*unit_name*/"模索路晶", /*bg_id*/500030, /*bg_name*/"ランドソル 繁華街", /*position*/0.0, /*face_type*/18);
INSERT INTO `unit_background` VALUES (/*unit_id*/107001, /*unit_name*/"ネネカ", /*bg_id*/500341, /*bg_name*/"ラビリンスギルド拠点", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/107101, /*unit_name*/"クリスティーナ・モーガン", /*bg_id*/500090, /*bg_name*/"ランドソル 王城入口", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/107501, /*unit_name*/"ペコリーヌ（サマー）", /*bg_id*/500164, /*bg_name*/"マルジェン海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/107601, /*unit_name*/"コッコロ（サマー）", /*bg_id*/500164, /*bg_name*/"マルジェン海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/107701, /*unit_name*/"スズメ（サマー）", /*bg_id*/500164, /*bg_name*/"マルジェン海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/107801, /*unit_name*/"キャル（サマー）", /*bg_id*/500164, /*bg_name*/"マルジェン海岸", /*position*/0.0, /*face_type*/6);
INSERT INTO `unit_background` VALUES (/*unit_id*/107901, /*unit_name*/"タマキ（サマー）", /*bg_id*/500284, /*bg_name*/"無人島", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108001, /*unit_name*/"ミフユ（サマー）", /*bg_id*/500284, /*bg_name*/"無人島", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108101, /*unit_name*/"シノブ（ハロウィン）", /*bg_id*/500264, /*bg_name*/"古城 ハロウィン", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108201, /*unit_name*/"ミヤコ（ハロウィン）", /*bg_id*/500264, /*bg_name*/"古城 ハロウィン", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108301, /*unit_name*/"ミサキ（ハロウィン）", /*bg_id*/505030, /*bg_name*/"ランドソル 繁華街 ハロウィン", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108401, /*unit_name*/"チカ（クリスマス）", /*bg_id*/500114, /*bg_name*/"サレンディア救護院_広間_クリスマス", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108501, /*unit_name*/"クルミ（クリスマス）", /*bg_id*/500114, /*bg_name*/"サレンディア救護院_広間_クリスマス", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108601, /*unit_name*/"アヤネ（クリスマス）", /*bg_id*/500114, /*bg_name*/"サレンディア救護院_広間_クリスマス", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108701, /*unit_name*/"ヒヨリ（ニューイヤー）", /*bg_id*/500553, /*bg_name*/"お正月神殿", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108801, /*unit_name*/"ユイ（ニューイヤー）", /*bg_id*/500553, /*bg_name*/"お正月神殿", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108901, /*unit_name*/"レイ（ニューイヤー）", /*bg_id*/500553, /*bg_name*/"お正月神殿", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/109001, /*unit_name*/"エリコ（バレンタイン）", /*bg_id*/500600, /*bg_name*/"キッチンスタジアム", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109101, /*unit_name*/"シズル（バレンタイン）", /*bg_id*/500600, /*bg_name*/"キッチンスタジアム", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109201, /*unit_name*/"アン", /*bg_id*/500133, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/109301, /*unit_name*/"ルゥ", /*bg_id*/500133, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109401, /*unit_name*/"グレア", /*bg_id*/500133, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109501, /*unit_name*/"クウカ（オーエド）", /*bg_id*/500650, /*bg_name*/"オーエド横丁", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109601, /*unit_name*/"ニノン（オーエド）", /*bg_id*/500650, /*bg_name*/"オーエド横丁", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/109701, /*unit_name*/"レム", /*bg_id*/500175, /*bg_name*/"ミステリオン森林", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/109801, /*unit_name*/"ラム", /*bg_id*/500175, /*bg_name*/"ミステリオン森林", /*position*/0.0, /*face_type*/12);
INSERT INTO `unit_background` VALUES (/*unit_id*/109901, /*unit_name*/"エミリア", /*bg_id*/500175, /*bg_name*/"ミステリオン森林", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/110001, /*unit_name*/"スズナ（サマー）", /*bg_id*/500683, /*bg_name*/"海_ステージ", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/110101, /*unit_name*/"イオ（サマー）", /*bg_id*/500683, /*bg_name*/"海_ステージ", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/110301, /*unit_name*/"サレン（サマー）", /*bg_id*/500164, /*bg_name*/"マルジェン海岸", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/110401, /*unit_name*/"マコト（サマー）", /*bg_id*/500710, /*bg_name*/"琉球風の海岸", /*position*/0.0, /*face_type*/6);
INSERT INTO `unit_background` VALUES (/*unit_id*/110501, /*unit_name*/"カオリ（サマー）", /*bg_id*/500710, /*bg_name*/"琉球風の海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/110601, /*unit_name*/"マホ（サマー）", /*bg_id*/500710, /*bg_name*/"琉球風の海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/110701, /*unit_name*/"アオイ（編入生）", /*bg_id*/500730, /*bg_name*/"聖テレサ女学院_正門", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/110801, /*unit_name*/"クロエ", /*bg_id*/500730, /*bg_name*/"聖テレサ女学院_正門", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/110901, /*unit_name*/"チエル", /*bg_id*/500730, /*bg_name*/"聖テレサ女学院_正門", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/111001, /*unit_name*/"ユニ", /*bg_id*/500730, /*bg_name*/"聖テレサ女学院_正門", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/111101, /*unit_name*/"キョウカ（ハロウィン）", /*bg_id*/500811, /*bg_name*/"屋敷_メインホール", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/111201, /*unit_name*/"ミソギ（ハロウィン）", /*bg_id*/500811, /*bg_name*/"屋敷_メインホール", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/111301, /*unit_name*/"ミミ（ハロウィン）", /*bg_id*/500811, /*bg_name*/"屋敷_メインホール", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/111401, /*unit_name*/"ルナ", /*bg_id*/500175, /*bg_name*/"ミステリオン森林", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/111501, /*unit_name*/"クリスティーナ（クリスマス）", /*bg_id*/500038, /*bg_name*/"ランドソル_繁華街_クリスマス", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/111601, /*unit_name*/"ノゾミ（クリスマス）", /*bg_id*/500038, /*bg_name*/"ランドソル_繁華街_クリスマス", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/111701, /*unit_name*/"イリヤ（クリスマス）", /*bg_id*/500038, /*bg_name*/"ランドソル_繁華街_クリスマス", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/111801, /*unit_name*/"ぺコリーヌ（ニューイヤー）", /*bg_id*/500910, /*bg_name*/"ランドソル_繁華街_駅伝", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/111901, /*unit_name*/"コッコロ（ニューイヤー）", /*bg_id*/500910, /*bg_name*/"ランドソル_繁華街_駅伝", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/112001, /*unit_name*/"キャル（ニューイヤー）", /*bg_id*/500910, /*bg_name*/"ランドソル_繁華街_駅伝", /*position*/0.0, /*face_type*/6);
INSERT INTO `unit_background` VALUES (/*unit_id*/112101, /*unit_name*/"スズメ（ニューイヤー）", /*bg_id*/500910, /*bg_name*/"ランドソル_繁華街_駅伝", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/112201, /*unit_name*/"カスミ（マジカル）", /*bg_id*/500010, /*bg_name*/"ランドソル_市街地_昼", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/112301, /*unit_name*/"シオリ（マジカル）", /*bg_id*/500010, /*bg_name*/"ランドソル_市街地_昼", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/112401, /*unit_name*/"ウヅキ（デレマス）", /*bg_id*/500920, /*bg_name*/"ムーサの町_昼", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/112501, /*unit_name*/"リン（デレマス）", /*bg_id*/500920, /*bg_name*/"ムーサの町_昼", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/112601, /*unit_name*/"ミオ（デレマス）", /*bg_id*/500920, /*bg_name*/"ムーサの町_昼", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/112701, /*unit_name*/"リン（レンジャー）", /*bg_id*/500995, /*bg_name*/"牧場 昼", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/112801, /*unit_name*/"マヒル（レンジャー）", /*bg_id*/500995, /*bg_name*/"牧場 昼", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/112901, /*unit_name*/"リノ（ワンダー）", /*bg_id*/501000, /*bg_name*/"本の世界_平原", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/113001, /*unit_name*/"アユミ（ワンダー）", /*bg_id*/501000, /*bg_name*/"本の世界_平原", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/113101, /*unit_name*/"ルカ（サマー）", /*bg_id*/501030, /*bg_name*/"ウィッシュビーチ", /*position*/0.0, /*face_type*/6);
INSERT INTO `unit_background` VALUES (/*unit_id*/113201, /*unit_name*/"アンナ（サマー）", /*bg_id*/501030, /*bg_name*/"ウィッシュビーチ", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/113301, /*unit_name*/"ナナカ（サマー）", /*bg_id*/501030, /*bg_name*/"ウィッシュビーチ", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/113401, /*unit_name*/"ハツネ（サマー）", /*bg_id*/501100, /*bg_name*/"ビーチグラウンド", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/113501, /*unit_name*/"ミサト（サマー）", /*bg_id*/501100, /*bg_name*/"ビーチグラウンド", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/113601, /*unit_name*/"ジュン（サマー）", /*bg_id*/500164, /*bg_name*/"マルジェン海岸", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/113701, /*unit_name*/"アカリ（エンジェル）", /*bg_id*/500010, /*bg_name*/"ランドソル_市街地_昼", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/113801, /*unit_name*/"ヨリ（エンジェル）", /*bg_id*/500010, /*bg_name*/"ランドソル_市街地_昼", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/113901, /*unit_name*/"ツムギ（ハロウィン）", /*bg_id*/501130, /*bg_name*/"ハロウィンパーク_昼", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/114001, /*unit_name*/"レイ（ハロウィン）", /*bg_id*/501130, /*bg_name*/"ハロウィンパーク_昼", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/114101, /*unit_name*/"マツリ（ハロウィン）", /*bg_id*/501130, /*bg_name*/"ハロウィンパーク_昼", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/114201, /*unit_name*/"モニカ（マジカル）", /*bg_id*/500010, /*bg_name*/"ランドソル_市街地_昼", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/114301, /*unit_name*/"トモ（マジカル）", /*bg_id*/500010, /*bg_name*/"ランドソル_市街地_昼", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/114401, /*unit_name*/"アキノ（クリスマス）", /*bg_id*/500874, /*bg_name*/"舞台_クリスマス_昼", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/114501, /*unit_name*/"サレン（クリスマス）", /*bg_id*/500874, /*bg_name*/"舞台_クリスマス_昼", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/114601, /*unit_name*/"ユカリ（クリスマス）", /*bg_id*/500874, /*bg_name*/"舞台_クリスマス_昼", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/114701, /*unit_name*/"ムイミ（ニューイヤー）", /*bg_id*/501162, /*bg_name*/"オーマの町_昼", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/115001, /*unit_name*/"ネネカ（ニューイヤー）", /*bg_id*/501162, /*bg_name*/"オーマの町_昼", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/115501, /*unit_name*/"コッコロ（儀装束）", /*bg_id*/500140, /*bg_name*/"プラノ平原", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/115601, /*unit_name*/"ユイ（儀装束）", /*bg_id*/500140, /*bg_name*/"プラノ平原", /*position*/0.0, /*face_type*/17);
INSERT INTO `unit_background` VALUES (/*unit_id*/115701, /*unit_name*/"カスミ（サマー）", /*bg_id*/500160, /*bg_name*/"マルジェン海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/115801, /*unit_name*/"リマ（シンデレラ）", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/115901, /*unit_name*/"マコト（シンデレラ）", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/116001, /*unit_name*/"マホ（シンデレラ）", /*bg_id*/500060, /*bg_name*/"自警団 拠点", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/116201, /*unit_name*/"クロエ（聖学祭）", /*bg_id*/500732, /*bg_name*/"聖テレサ女学院_正門_聖学祭", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/116301, /*unit_name*/"チエル（聖学祭）", /*bg_id*/500732, /*bg_name*/"聖テレサ女学院_正門_聖学祭", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/116501, /*unit_name*/"イノリ（タイムトラベル）", /*bg_id*/500010, /*bg_name*/"ランドソル_市街地_昼", /*position*/0.0, /*face_type*/18);
INSERT INTO `unit_background` VALUES (/*unit_id*/116601, /*unit_name*/"カヤ（タイムトラベル）", /*bg_id*/500010, /*bg_name*/"ランドソル_市街地_昼", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/116701, /*unit_name*/"アオイ（作業服）", /*bg_id*/501340, /*bg_name*/"おもちゃ工場", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/116801, /*unit_name*/"タマキ（作業服）", /*bg_id*/501340, /*bg_name*/"おもちゃ工場", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/116901, /*unit_name*/"ミフユ（作業服）", /*bg_id*/501340, /*bg_name*/"おもちゃ工場", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/117001, /*unit_name*/"エリコ（サマー）", /*bg_id*/500160, /*bg_name*/"マルジェン海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/117101, /*unit_name*/"シズル（サマー）", /*bg_id*/500160, /*bg_name*/"マルジェン海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/117201, /*unit_name*/"ノゾミ（サマー）", /*bg_id*/501363, /*bg_name*/"サマーフェス会場", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/117301, /*unit_name*/"チカ（サマー）", /*bg_id*/501363, /*bg_name*/"サマーフェス会場", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/117401, /*unit_name*/"ツムギ（サマー）", /*bg_id*/501363, /*bg_name*/"サマーフェス会場", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/117501, /*unit_name*/"ミツキ（オーエド）", /*bg_id*/501380, /*bg_name*/"オーエド_診察室_昼", /*position*/0.0, /*face_type*/6);
INSERT INTO `unit_background` VALUES (/*unit_id*/117601, /*unit_name*/"ユキ（オーエド）", /*bg_id*/501380, /*bg_name*/"オーエド_診察室_昼", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/180101, /*unit_name*/"ヒヨリ（プリンセス）", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/180201, /*unit_name*/"ユイ（プリンセス）", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/180301, /*unit_name*/"レイ（プリンセス）", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/180401, /*unit_name*/"ぺコリーヌ（プリンセス）", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/180501, /*unit_name*/"コッコロ（プリンセス）", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/180601, /*unit_name*/"キャル（プリンセス）", /*bg_id*/500130, /*bg_name*/"エステレラ街道", /*position*/0.0, /*face_type*/18);
INSERT INTO `unit_background` VALUES (/*unit_id*/180701, /*unit_name*/"ハツネ＆シオリ", /*bg_id*/501370, /*bg_name*/"滝壺_昼", /*position*/0.0, /*face_type*/2);
